M48
; DRILL file {KiCad (6.0.8)} date Tue Apr 18 21:35:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-18T21:35:47-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1201
%
G90
G05
T1
X7.5119Y-4.1401
X8.1719Y-4.1401
T2
X6.7575Y-4.1838
X6.9425Y-4.1838
T0
M30
