M48
; DRILL file {KiCad (6.0.8)} date Thu Apr 27 21:46:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-27T21:46:57-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1201
%
G90
G05
T1
X6.08Y-4.2086
X6.78Y-4.2086
X7.48Y-4.2086
T2
X5.2375Y-4.2138
X5.4225Y-4.2138
T0
M30
